[package]
version = "0.1.0"
name = "price-program"
edition = "2024"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "5.1.0"
price-lib = { path = "../../lib/price", features = ["zkvm"] }
borsh = { version = "1.5", default-features = false, features = ["derive"] }

[target.'cfg(target_os = "zkvm")'.dependencies]
indexed-merkle-map = { git = "https://github.com/silvanaone/silvana", package = "indexed-merkle-map", features = ["zkvm"] }
